"""Add telegram_id

Revision ID: c1f85181c904
Revises: 4b39d0683da3
Create Date: 2025-05-15 22:48:33.288386

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1f85181c904"
down_revision: Union[str, None] = "4b39d0683da3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram_id", sa.String(length=255), nullable=True)
    )
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["telegram_id"])
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
